---
- hosts: default
  gather_facts: false

  tasks:
    - name: Copy required files
      copy:
        src: "{{ item }}"
        dest: .
      loop:
        - Dockerfile
        - docker-compose.yml
        - .ldif

    - name: Replace the advertised endpoint
      replace:
        path: docker-compose.yml
        regexp: 'bootstrap-server-mapping=(.+),(.+),(.+):'
        replace: 'bootstrap-server-mapping=\1,\2,kafka.example.org:'

    - name: Set up the Docker services
      docker_compose:
        project_name: kafka
        project_src: .
        state: present
      become: true
